// SendMailConfigurationDlg.cpp : implementation file
//

#include "stdafx.h"
#include "uimager.h"
#include "VideoDeviceDoc.h"
#include "SendMailConfigurationDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

#ifdef VIDEODEVICEDOC

/////////////////////////////////////////////////////////////////////////////
// CSendMailConfigurationDlg dialog


CSendMailConfigurationDlg::CSendMailConfigurationDlg(CVideoDeviceDoc* pDoc)
	: CDialog(CSendMailConfigurationDlg::IDD, NULL)
{
	//{{AFX_DATA_INIT(CSendMailConfigurationDlg)
		// NOTE: the ClassWizard will add member initialization here
	//}}AFX_DATA_INIT
	m_pDoc = pDoc;
}


void CSendMailConfigurationDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CSendMailConfigurationDlg)
		// NOTE: the ClassWizard will add DDX and DDV calls here
	//}}AFX_DATA_MAP
}


BEGIN_MESSAGE_MAP(CSendMailConfigurationDlg, CDialog)
	//{{AFX_MSG_MAP(CSendMailConfigurationDlg)
	ON_BN_CLICKED(IDC_BUTTON_TEST, OnButtonTest)
	ON_CBN_SELCHANGE(IDC_AUTH_METHOD, OnSelchangeAuthMethod)
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CSendMailConfigurationDlg message handlers

BOOL CSendMailConfigurationDlg::OnInitDialog() 
{
	CDialog::OnInitDialog();

	// To Email
	CEdit* pEdit = (CEdit*)GetDlgItem(IDC_RECEIVER_MAIL);
	pEdit->SetWindowText(m_pDoc->m_MovDetSendMailConfiguration.m_sTo);

	// Send HTML Email?
	CButton* pCheck = (CButton*)GetDlgItem(IDC_HTML);
	pCheck->SetCheck(m_pDoc->m_MovDetSendMailConfiguration.m_bHTML ? 1 : 0);

	// Attachment possibilities
	CComboBox* pComboBox = (CComboBox*)GetDlgItem(IDC_ATTACHMENT);
    pComboBox->AddString(_T("None"));
    pComboBox->AddString(_T("AVI Detection"));
    pComboBox->AddString(_T("Animated GIF Detection"));
    pComboBox->AddString(_T("AVI + Animated GIF Detections"));
	pComboBox->SetCurSel((int)m_pDoc->m_MovDetSendMailConfiguration.m_AttachmentType);

	// From Name
	pEdit = (CEdit*)GetDlgItem(IDC_SENDER_NAME);
	pEdit->SetWindowText(m_pDoc->m_MovDetSendMailConfiguration.m_sFromName);

	// From Email
	pEdit = (CEdit*)GetDlgItem(IDC_SENDER_MAIL);
	pEdit->SetWindowText(m_pDoc->m_MovDetSendMailConfiguration.m_sFrom);

	// Server Name
	pEdit = (CEdit*)GetDlgItem(IDC_HOST_NAME);
	pEdit->SetWindowText(m_pDoc->m_MovDetSendMailConfiguration.m_sHost);

	// Server Port
	pEdit = (CEdit*)GetDlgItem(IDC_HOST_PORT);
	CString sPort;
	sPort.Format(_T("%i"), m_pDoc->m_MovDetSendMailConfiguration.m_nPort);
	pEdit->SetWindowText(sPort);

	// Auth Methods
    int index = 0;
	BOOL bAuthenticated = (m_pDoc->m_MovDetSendMailConfiguration.m_Auth != CPJNSMTPConnection::AUTH_NONE);
	pComboBox = (CComboBox*)GetDlgItem(IDC_AUTH_METHOD);
	pComboBox->AddString(ML_STRING(1827, "None"));		// CPJNSMTPConnection::AUTH_NONE = 0
														// use no authentication with the server
	pComboBox->SetItemData(index++, CPJNSMTPConnection::AUTH_NONE);
    pComboBox->AddString(ML_STRING(1828, "CRAM MD5"));	// CPJNSMTPConnection::AUTH_CRAM_MD5 = 1
														// CRAM (Challenge Response Authention Method) MD5 (RFC 2195).
														// A challenge is generated by the server, and the response is
														// the MD5 HMAC of the challenge using the password as the key.
														// The username is also supplied in the challenge response.
	pComboBox->SetItemData(index++, CPJNSMTPConnection::AUTH_CRAM_MD5);
    pComboBox->AddString(ML_STRING(1829, "AUTH LOGIN"));// CPJNSMTPConnection::AUTH_LOGIN = 2
														// username and password are simply base64 encoded responses to the server
	pComboBox->SetItemData(index++, CPJNSMTPConnection::AUTH_LOGIN);
    pComboBox->AddString(ML_STRING(1830, "AUTH PLAIN"));// CPJNSMTPConnection::AUTH_PLAIN = 3
														// username and password are sent in the clear to the server
	pComboBox->SetItemData(index++, CPJNSMTPConnection::AUTH_PLAIN);
    pComboBox->AddString(ML_STRING(1831, "NTLM"));		// CPJNSMTPConnection::AUTH_NTLM = 4
														// use the MS NTLM authentication protocol
	pComboBox->SetItemData(index++, CPJNSMTPConnection::AUTH_NTLM);
	pComboBox->AddString(ML_STRING(1832, "Auto Detect"));// CPJNSMTPConnection::AUTH_AUTO = 5
														// try to auto negotiate the authentication protocol to use,
														// the order used will be as decided by the "ChooseAuthenticationMethod"
														// virtual method
	pComboBox->SetItemData(index++, CPJNSMTPConnection::AUTH_AUTO);
	for (index = 0 ; index < pComboBox->GetCount() ; index++)
	{
		if (pComboBox->GetItemData(index) == m_pDoc->m_MovDetSendMailConfiguration.m_Auth)
		{
			pComboBox->SetCurSel(index);
			break;
		}
	}

	// Username and Password
	pEdit = (CEdit*)GetDlgItem(IDC_AUTH_USERNAME);
	pEdit->SetWindowText(m_pDoc->m_MovDetSendMailConfiguration.m_sUsername);
	pEdit->EnableWindow(bAuthenticated);
	pEdit = (CEdit*)GetDlgItem(IDC_AUTH_PASSWORD);
	pEdit->SetWindowText(m_pDoc->m_MovDetSendMailConfiguration.m_sPassword);
	pEdit->EnableWindow(bAuthenticated);

	return TRUE;  // return TRUE unless you set the focus to a control
	              // EXCEPTION: OCX Property Pages should return FALSE
}

void CSendMailConfigurationDlg::OnSelchangeAuthMethod() 
{
	CComboBox* pComboBox = (CComboBox*)GetDlgItem(IDC_AUTH_METHOD);
	CPJNSMTPConnection::AuthenticationMethod Authentication =
				(CPJNSMTPConnection::AuthenticationMethod)pComboBox->GetItemData(pComboBox->GetCurSel());
	BOOL bAuthenticated = (Authentication != CPJNSMTPConnection::AUTH_NONE);
	CEdit* pEdit = (CEdit*)GetDlgItem(IDC_AUTH_USERNAME);
	pEdit->EnableWindow(bAuthenticated);
	pEdit = (CEdit*)GetDlgItem(IDC_AUTH_PASSWORD);
	pEdit->EnableWindow(bAuthenticated);
}

void CSendMailConfigurationDlg::CopyToDoc()
{
	CString sText;

	CEdit* pEdit = (CEdit*)GetDlgItem(IDC_RECEIVER_MAIL);
	pEdit->GetWindowText(sText);
	m_pDoc->m_MovDetSendMailConfiguration.m_sTo = sText;

	CButton* pCheck = (CButton*)GetDlgItem(IDC_HTML);
	m_pDoc->m_MovDetSendMailConfiguration.m_bHTML = pCheck->GetCheck();

	CComboBox* pComboBox = (CComboBox*)GetDlgItem(IDC_ATTACHMENT);
	m_pDoc->m_MovDetSendMailConfiguration.m_AttachmentType =
			(CVideoDeviceDoc::AttachmentType)pComboBox->GetCurSel();

	pEdit = (CEdit*)GetDlgItem(IDC_SENDER_NAME);
	pEdit->GetWindowText(sText);
	m_pDoc->m_MovDetSendMailConfiguration.m_sFromName = sText;

	pEdit = (CEdit*)GetDlgItem(IDC_SENDER_MAIL);
	pEdit->GetWindowText(sText);
	m_pDoc->m_MovDetSendMailConfiguration.m_sFrom = sText;

	pEdit = (CEdit*)GetDlgItem(IDC_HOST_NAME);
	pEdit->GetWindowText(sText);
	m_pDoc->m_MovDetSendMailConfiguration.m_sHost = sText;

	pEdit = (CEdit*)GetDlgItem(IDC_HOST_PORT);
	pEdit->GetWindowText(sText);
	int nPort = _tcstol(sText.GetBuffer(0), NULL, 10);
	sText.ReleaseBuffer();
	if (nPort > 0 && nPort <= 65535) // Port 0 is Reserved
		m_pDoc->m_MovDetSendMailConfiguration.m_nPort = nPort;
	else
		m_pDoc->m_MovDetSendMailConfiguration.m_nPort = 25;

	pComboBox = (CComboBox*)GetDlgItem(IDC_AUTH_METHOD);
	m_pDoc->m_MovDetSendMailConfiguration.m_Auth =
			(CPJNSMTPConnection::AuthenticationMethod)pComboBox->GetItemData(pComboBox->GetCurSel());

	pEdit = (CEdit*)GetDlgItem(IDC_AUTH_USERNAME);
	pEdit->GetWindowText(sText);
	m_pDoc->m_MovDetSendMailConfiguration.m_sUsername = sText;

	pEdit = (CEdit*)GetDlgItem(IDC_AUTH_PASSWORD);
	pEdit->GetWindowText(sText);
	m_pDoc->m_MovDetSendMailConfiguration.m_sPassword = sText;
}

void CSendMailConfigurationDlg::OnOK() 
{
	CopyToDoc();
	CDialog::OnOK();
}

void CSendMailConfigurationDlg::OnButtonTest() 
{
	CopyToDoc();

	int res = 0;

	if (m_pDoc->m_MovDetSendMailConfiguration.m_sHost.IsEmpty()||
		m_pDoc->m_MovDetSendMailConfiguration.m_sFrom.IsEmpty() ||
		m_pDoc->m_MovDetSendMailConfiguration.m_sTo.IsEmpty()) 
		::AfxMessageBox(ML_STRING(1406, "Please Enter A Host Name, a From and a To Address"));
	else 
	{
		BeginWaitCursor();

		CPJNSMTPMessage* pMessage = NULL;
		try
		{
			// Subject
			CTime Time = CTime::GetCurrentTime();
			CString sSubject(Time.Format(_T("Movement Detection on %A, %d %B %Y at %H:%M:%S")));
			m_pDoc->m_MovDetSendMailConfiguration.m_sSubject = sSubject;

			if (m_pDoc->m_MovDetSendMailConfiguration.m_bHTML == FALSE)
			{
				m_pDoc->m_MovDetSendMailConfiguration.m_bMime = FALSE;
				m_pDoc->m_MovDetSendMailConfiguration.m_sBody = _T("Movement Detection Test Email");

				// No Attachment(s)
				m_pDoc->m_MovDetSendMailConfiguration.m_sFiles = _T("");

				// Create the message
				pMessage = m_pDoc->CreateEmailMessage();
			}
			else
			{
				m_pDoc->m_MovDetSendMailConfiguration.m_bMime = TRUE;
				m_pDoc->m_MovDetSendMailConfiguration.m_sFiles = _T("");
				m_pDoc->m_MovDetSendMailConfiguration.m_sBody = _T("");

				// Create the message
				pMessage = m_pDoc->CreateEmailMessage();

				for (int i = 0 ; i < pMessage->GetNumberOfBodyParts() ; i++)
					pMessage->RemoveBodyPart(i);

				// Setup all the body parts we want
				CPJNSMTPBodyPart related;
				related.SetContentType(_T("multipart/related"));

				CPJNSMTPBodyPart html;
				html.SetText(_T("<p><b>Movement Detection Test Email</b></p>"));
				html.SetContentType(_T("text/html"));

				related.AddChildBodyPart(html);
				pMessage->AddBodyPart(related);
				pMessage->GetBodyPart(0)->SetContentLocation(_T("http://localhost"));
			}

			// Init Connection class
			CVideoDeviceDoc::CSaveFrameListSMTPConnection connection;

			// Auto connect to the internet?
			if (m_pDoc->m_MovDetSendMailConfiguration.m_bAutoDial)
				connection.ConnectToInternet();

			CString sHost;
			BOOL bSend = TRUE;
			if (m_pDoc->m_MovDetSendMailConfiguration.m_bDNSLookup)
			{
				if (pMessage->GetNumberOfRecipients() == 0)
				{
					EndWaitCursor();
					CString sMsg(ML_STRING(1410, "At least one recipient must be specified to use the DNS lookup option\n"));
					TRACE(sMsg);
					::AfxMessageBox(sMsg);
					bSend = FALSE;
				}
				else
				{
					CString sAddress = pMessage->GetRecipient(0)->m_sEmailAddress;
					int nAmpersand = sAddress.Find(_T("@"));
					if (nAmpersand == -1)
					{
						EndWaitCursor();
						CString sMsg;
						sMsg.Format(ML_STRING(1411, "Unable to determine the domain for the email address %s\n"), sAddress);
						TRACE(sMsg);
						::AfxMessageBox(sMsg);
						bSend = FALSE;
					}
					else
					{
						// We just pick the first MX record found, other implementations could ask the user
						// or automatically pick the lowest priority record
						CString sDomain(sAddress.Right(sAddress.GetLength() - nAmpersand - 1));
						CStringArray servers;
						CWordArray priorities;
						if (!connection.MXLookup(sDomain, servers, priorities))
						{
							EndWaitCursor();
							CString sMsg;
							sMsg.Format(ML_STRING(1413, "Unable to perform a DNS MX lookup for the domain %s, Error Code:%d\n"), sDomain, GetLastError());
							TRACE(sMsg);
							::AfxMessageBox(sMsg);
							bSend = FALSE;
						}
						else
							sHost = servers.GetAt(0);
					}
				}
			}
			else
				sHost = m_pDoc->m_MovDetSendMailConfiguration.m_sHost;

			// Connect and send the message
			if (bSend)
			{
				connection.SetBoundAddress(m_pDoc->m_MovDetSendMailConfiguration.m_sBoundIP);
				if (m_pDoc->m_MovDetSendMailConfiguration.m_sUsername == _T("") &&
					m_pDoc->m_MovDetSendMailConfiguration.m_sPassword == _T(""))
				{
					connection.Connect(	sHost,
										CPJNSMTPConnection::AUTH_NONE,
										m_pDoc->m_MovDetSendMailConfiguration.m_sUsername,
										m_pDoc->m_MovDetSendMailConfiguration.m_sPassword,
										m_pDoc->m_MovDetSendMailConfiguration.m_nPort);
				}
				else
				{
					connection.Connect(	sHost,
										m_pDoc->m_MovDetSendMailConfiguration.m_Auth,
										m_pDoc->m_MovDetSendMailConfiguration.m_sUsername,
										m_pDoc->m_MovDetSendMailConfiguration.m_sPassword,
										m_pDoc->m_MovDetSendMailConfiguration.m_nPort);
				}
				connection.SendMessage(*pMessage);
				EndWaitCursor();
				::AfxMessageBox(ML_STRING(1409, "Success: Email Sent."), MB_ICONINFORMATION);
			}

			// Auto disconnect from the internet
			if (m_pDoc->m_MovDetSendMailConfiguration.m_bAutoDial)
				connection.CloseInternetConnection();

			// Sending Interrupted?
			if (connection.m_bDoExit)
			{
				connection.Disconnect(FALSE);	// Disconnect no Gracefully,
												// otherwise the thread blocks
												// long time to get a answer!
				res = -1;
			}
			else
				res = 1;

			// Clean-up
			if (pMessage)
				delete pMessage;
		}
		catch (CPJNSMTPException* pEx)
		{
			// Clean-up
			if (pMessage)
				delete pMessage;

			// Display the error
			EndWaitCursor();
			CString sMsg;
			sMsg.Format(ML_STRING(1414, "An error occured sending the message, Error:%x\nDescription:%s\n"),
						pEx->m_hr,
						pEx->GetErrorMessage());
			TRACE(sMsg);
			::AfxMessageBox(sMsg, MB_ICONSTOP);
			pEx->Delete();
		}
	}
}

#endif
