#if !defined(AFX_REMOTECAM_H__EE39F455_BD32_4877_9A24_4C423F05B7DB__INCLUDED_)
#define AFX_REMOTECAM_H__EE39F455_BD32_4877_9A24_4C423F05B7DB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRemoteCam wrapper class

class CRemoteCam : public CWnd
{
protected:
	DECLARE_DYNCREATE(CRemoteCam)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8cf6679, 0x5bb3, 0x4ef4, { 0xa7, 0x73, 0xc4, 0x10, 0xdc, 0x56, 0x53, 0x1c } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{	
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID);
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID, pPersist, bStorage, bstrLicKey);
	}

// Attributes
public:
	CString GetHost();
	void SetHost(LPCTSTR);
	long GetPort();
	void SetPort(long);
	long GetMaxFrames();
	void SetMaxFrames(long);
	BOOL GetDisableResend();
	void SetDisableResend(BOOL);

// Operations
public:
	void AboutBox();
	void PropertyPage(HWND hParentWnd);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_REMOTECAM_H__EE39F455_BD32_4877_9A24_4C423F05B7DB__INCLUDED_)
